CREATE TABLE SCHOOLS (
  SCHOOL_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NAME VARCHAR NOT NULL,
  ADDRESS_LINE_1 VARCHAR NOT NULL,
  ADDRESS_LINE_2 VARCHAR NOT NULL,
  VILLAGE_CITY VARCHAR NOT NULL,
  DISTRICT VARCHAR NOT NULL,
  STATE VARCHAR NOT NULL,
  PIN VARCHAR NOT NULL,
  EMAIL VARCHAR NOT NULL,
  STAFF_ID INTEGER REFERENCES ASPNETUSERS(ID) 
);

CREATE TABLE TEACHERS (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  FIRST_NAME VARCHAR NOT NULL,
  LAST_NAME VARCHAR NOT NULL,
  CONTACT VARCHAR,
  EMAIL_ID VARCHAR
);

CREATE TABLE CLASS (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NAME VARCHAR NOT NULL
);

CREATE TABLE SCHOLARSHIPS_DETAILS (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  SCHOOL_ID INTEGER REFERENCES SCHOOLS(SCHOOL_ID),
    CLASS_ID INTEGER REFERENCES CLASS(ID),
    STAFF_ID INTEGER REFERENCES ASPNETUSERS(ID),
    TEACHER_ID INTEGER REFERENCES TEACHERS(ID),
    ACADEMIC_YEAR VARCHAR NOT NULL,
    TOTAL_STUDENTS INTEGER NOT NULL
);

CREATE TABLE PAYMENT_DETAILS (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  SCHOLARSHIP_ID INTEGER REFERENCES SCHOLARSHIPS_DETAILS(ID),
  TOTAL_PAYMENT DECIMAL,
  PAID DECIMAL,
  PAYMENT_STATUS BOOLEAN
);